app.swagger_ui:
    path: /
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# config/routes.yaml
app.swagger:
    path: /json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }